server:
    port: 8090
spring:
    datasource:
        url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
        username: ${PGUSER}
        password: ${PGPASSWORD}
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create
    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB